SELECT p.PRODUCT_ID, p.PRODUCT_NAME, (p.PRICE * q.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) q ON p.PRODUCT_ID = q.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID ASC;