SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) max_fish ON i.FISH_TYPE = max_fish.FISH_TYPE AND i.LENGTH = max_fish.MAX_LENGTH
ORDER BY i.ID ASC;